name: Build & Push to Docker Hub

on:
  push:
    branches: [main] # 推送到 main 分支时触发
    tags: ["v*"] # 也可以打 tag 发布版本
  pull_request: # PR 时仅构建不推送
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/admin-vue3-ts # 改成自己的仓库名

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉源码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 设置 QEMU / Buildx 以便多架构构建（可选）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. 登录（非 PR 才登录）
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. 生成镜像元数据（tag）
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      # 5. 构建并推送
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64 # 需要多架构时取消注释
          cache-from: type=gha
          cache-to: type=gha,mode=max
