name: Build & Push to Docker Hub

on:
  push:
    tags:
      - "v*" # 仅匹配 v1.0.0 / v2025.07.30 等形式的 tag

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/admin-vue3-ts # 改成自己的仓库名

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉源码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 设置 QEMU / Buildx 以便多架构构建（可选）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. 登录（非 PR 才登录）
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. 生成镜像元数据（tag、label）
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/nest-serve
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      # 5. 构建并推送
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
